version: '3.7'
services:
  api:
    container_name: api
    hostname: localhost
    domainname: localhost
    restart: always
    build: .
    command: npm run nx -- serve api --host 0.0.0.0
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3333:3333"
    expose:
      - "3333"
    networks:
      backend:
        aliases:
          - api
          - api.localhost
  frontend:
    container_name: frontend
    hostname: localhost
    domainname: localhost
    restart: always
    build: .
    command: npm run nx -- serve frontend --host 0.0.0.0
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "4200:4200"
    links:
      - api
    networks:
      backend:
        aliases:
          - frontend
          - frontend.localhost
    depends_on:
      - api

networks:
  backend:
    driver: bridge

#    depends_on:
#      - mongodb
#    environment:
#      DATABASE_URL: postgres://todoapp@postgres/todos
#  mongodb:
#    image: mongodb:latest
#    environment:
#      MONGODB_USER: mongo-user
#      MONGODB_PASS: mongo-pass
